// <auto-generated />
using Customer.Services.ContactAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Customer.Services.ContactAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220518084817_SeedContacts")]
    partial class SeedContacts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Customer.Services.ContactAPI.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "umer.waqar@live.com",
                            PersonalNumber = "202218051234",
                            Phone = "+46768351295"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john.doe@noreply.com",
                            PersonalNumber = "201218051234",
                            Phone = "+46769120000"
                        },
                        new
                        {
                            Id = 3,
                            Email = "chris.jericho@wwe.com",
                            PersonalNumber = "201018051234",
                            Phone = "+46760000000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
